spring:
  datasource:
    url: "jdbc:mysql://localhost:3308/identity_service"
    username: root
    password: root
  application:
    name: identity-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
  servlet:
    context-path: /identity
jwt:
  signerKey: "jcwIA57vo9jBNdTNPZaK5rth33TWtXK6PJWH/87GiX+JwzyYgFWO6hhjf2J8B8dk"
  valid-duration: 20 # in second
  refreshable-duration:  120 # in seconds
